<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>フォーム</title>
</head>
<body>
<p> 入力フォーム </p>
<form action="confirm.php" method="post">
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>
	<input type="text" name="yourname"><br>

</form>

</body>
</html>